# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: trailing-whitespace
          - id: check-added-large-files
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.3
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
    - repo: https://github.com/hadolint/hadolint
      rev: v2.9.0
      hooks:
          - id: hadolint-docker
    - repo: https://github.com/spezifisch/pre-commit-php
      rev: 0.7.0
      hooks:
          - id: docker-phpmd
            args: ["ansi", "cleancode,codesize,controversial,design,unusedcode"]
