networks:
    mb-test:

volumes:
    test-postgres-data: {}
    test-vendor: {}

services:
    test-db:
        image: postgres:13-alpine
        networks:
            - mb-test
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: mb_test
        volumes:
            - type: volume
              source: test-postgres-data
              target: /var/lib/postgresql/data

    testrunner:
        build:
            context: ./app
            dockerfile: docker/Dockerfile.test
        networks:
            - mb-test
        depends_on:
            - test-db
        environment:
            APP_ENV: test
            POSTGRES_VERSION: 13
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: mb_test
        volumes:
            - type: bind
              source: ./app
              target: /app/
            - type: volume
              source: test-vendor
              target: /app/vendor
